# Generated by Django 3.2.11 on 2023-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
