# Generated by Django 3.2.11 on 2023-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_wa',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
