# Generated by Django 3.2.11 on 2022-10-16 16:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, unique=True)),
                ('waktu_awal', models.DateTimeField(blank=True, null=True)),
                ('waktu_akhir', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'aktif'), ('tidak aktif', 'tidak aktif')], default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(choices=[('Informatika', 1), ('Teknik Komputer', 2), ('Teknik Elektro', 3), ('Studi Islam Interdisipliner', 4), ('Agribisnis', 5), ('Farmasi', 6), ('Pendidikan Guru Sekolah Dasar', 7), ('Pendidikan Bahasa Inggris', 8), ('Menejemen', 9), ('Akuntansi', 10), ('Teknologi Hasil Pertanian', 11)], default='INF', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=26)),
                ('jk', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='Laki-Laki', max_length=9)),
                ('domisili', models.CharField(default='', max_length=50)),
                ('nim', models.PositiveBigIntegerField(unique=True)),
                ('tgl_lahir', models.DateField()),
                ('tpt_lahir', models.CharField(max_length=26)),
                ('no_wa', models.PositiveBigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('visi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('misi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='panitia.agenda')),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagian', to='panitia.jurusan')),
            ],
        ),
    ]
