# Generated by Django 3.2.11 on 2022-06-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='nim',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='kandidat',
            name='no_wa',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
