# Generated by Django 3.2.11 on 2022-10-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='vote',
            field=models.BigIntegerField(default=0),
        ),
    ]
