# Generated by Django 3.2.11 on 2022-06-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220623_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='status',
        ),
    ]
