# Generated by Django 3.2.11 on 2022-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220623_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='tgl_lahir',
            field=models.DateField(),
        ),
    ]
