# Generated by Django 3.2.11 on 2022-10-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0003_alter_kandidat_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='vote',
            field=models.PositiveBigIntegerField(default=0, max_length=100),
        ),
    ]
