# Generated by Django 3.2.11 on 2022-09-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='panitia.agenda'),
        ),
    ]
