# Generated by Django 3.2.11 on 2022-11-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_alter_kandidat_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidat',
            name='vote',
        ),
    ]
