# Generated by Django 3.2.11 on 2022-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_remove_kandidat_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(default='static/img/icon.png', upload_to='images/'),
        ),
    ]
