# Generated by Django 3.2.11 on 2022-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0007_alter_kandidat_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
