# Generated by Django 3.2.11 on 2022-12-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0008_alter_kandidat_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidat',
            name='foto',
        ),
    ]
