# Generated by Django 3.2.11 on 2022-12-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0010_agenda_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='owner',
        ),
    ]
