# Generated by Django 3.2.11 on 2022-12-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panitia', '0011_remove_agenda_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='panitia_agenda', to='account.user'),
            preserve_default=False,
        ),
    ]
