# Generated by Django 3.2.11 on 2023-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0013_kandidat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
