# Generated by Django 3.2.11 on 2022-06-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0003_alter_kandidat_tgl_lahir'),
        ('pemilih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='agenda',
        ),
        migrations.AddField(
            model_name='vote',
            name='kandidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to='panitia.kandidat'),
        ),
    ]
