# Generated by Django 3.2.11 on 2022-07-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_vote'),
        ('pemilih', '0002_auto_20220623_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ketika', to='panitia.agenda'),
        ),
    ]
