# Generated by Django 3.2.11 on 2022-09-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilih', '0003_vote_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='agenda',
        ),
    ]
