# Generated by Django 3.2.11 on 2022-11-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_remove_kandidat_vote'),
        ('pemilih', '0003_remove_poll_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='vote',
        ),
        migrations.AddField(
            model_name='poll',
            name='kandidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilih', to='panitia.kandidat'),
        ),
    ]
