# Generated by Django 3.2.11 on 2022-12-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilih', '0004_auto_20221201_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='kandidat',
        ),
    ]
