# Generated by Django 3.2.11 on 2022-12-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_remove_kandidat_vote'),
        ('pemilih', '0005_remove_poll_kandidat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='SelectAgenda',
        ),
        migrations.CreateModel(
            name='BuatPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_agenda', to='pemilih.selectagenda')),
                ('kandidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_kandidat', to='panitia.kandidat')),
            ],
        ),
    ]
