# Generated by Django 3.2.11 on 2022-12-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_remove_kandidat_vote'),
        ('pemilih', '0006_auto_20221202_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='panitia.agenda')),
                ('kandidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilih', to='panitia.kandidat')),
            ],
        ),
        migrations.AlterField(
            model_name='buatpoll',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_agenda', to='pemilih.poll'),
        ),
        migrations.DeleteModel(
            name='SelectAgenda',
        ),
    ]
