# Generated by Django 3.2.11 on 2022-12-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_remove_kandidat_vote'),
        ('pemilih', '0007_auto_20221202_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='kandidat',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pilih', to='panitia.kandidat'),
        ),
        migrations.DeleteModel(
            name='BuatPoll',
        ),
    ]
